apiVersion: v1
kind: ConfigMap
metadata:
  name: service-point
  namespace: "{{ .Values.global.xraylab.namespace }}"
data:
  url: "{{ .Values.odf.serviceUrl }}"
  url-external: "{{ .Values.odf.externalUrl }}.apps.{{ .Values.global.datacenter.clustername }}.{{ .Values.global.datacenter.domain }}"
