kind: ConfigMap
apiVersion: v1
metadata:
  name: additional-profiles
  namespace: opendatahub
  labels:
    jupyterhub: singleuser-profiles
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  jupyterhub-singleuser-profiles.yaml: |-
    profiles:
    - name: preload repos
      env:
        - name: JUPYTER_PRELOAD_REPOS
          value: https://github.com/red-hat-data-services/xraylab_notebooks.git
