global:
  pattern: xray
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  # XRay configuration for service-point config map
  # Found in charts/datacenter/xraylab/templates
  #   datacenter:
  #     cloudProvider: <aws,azure,gcp>
  #     storageClassName: <gp2>
  #     region: <us-east-1>
  #     clustername: <cluster-name>
  #     domain: <domain>

  datacenter:
    cloudProvider: PROVIDE_CLOUD_PROVIDER
    storageClassName: PROVIDE_STORAGE_CLASS
    region: PROVIDE_REGION
    clustername: PROVIDE_CLUSTERNAME
    domain: PROVIDE_DNS_DOMAIN

  xraylab:
    namespace: "xraylab-1"

    s3:
      # Values for S3 bucket access
      # Replace <region> with AWS region where S3 bucket was created
      # Replace <cluster-name> and <domain> with your OpenShift cluster values
      # bucketSource: "https://s3.<region>.amazonaws.com/com.redhat.claudiol.xray-source"
      bucketSource: PROVIDE_S3_BUCKETSOURCE
      # Bucket base name used for xray images
      bucketBaseName: "xraylab-1"

main:
  clusterGroupName: datacenter
