global:
  pattern: common
  valuesDirectoryURL: https://github.com/pattern-clone/common/raw/main
  options:
    useCSV: True
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: example

  proposedOptions:
    manageGitops: True
    isHubCluster: True


deployRBAC: true
createJob: true
createCustomRole: false

#Configurations for RoleBindings
pattern:
  namespace: xraylab-1
rbac:
  roleName: admin

gitopsServiceAccount: openshift-gitops-argocd-application-controller
gitopsNameSpace: openshift-gitops
ocImage: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

#Configurations for OCP/k8s job templates
job:
- name: grafana-clusterviewer
  args: "oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount -n xraylab-1"
  serviceAccountName: openshift-gitops-argocd-application-controller

- name: odf-node-labeler
  args: "oc label nodes -l node-role.kubernetes.io/worker= cluster.ocs.openshift.io/openshift-storage="
  serviceAccountName: openshift-gitops-argocd-application-controller

#Configurations for custom role
role:
  cluster: false
  name: ""
  namespace: "openshift-gitops"
  resources: "pods"
  verbs:
    - '"get"'
    - '"watch"'
    - '"list"'

#  managedClusterGroups:
#  - name: factory
#    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#    # Location of values-global.yaml, values-{name}.yaml, values-{app}.yaml
#    # valuesDirectoryURL: https://github.com/dagger-refuse-cool/edge-gitops/raw/main/
#    targetRevision: main
#    path: applications/factory
#    helmOverrides:
#    - name: clusterGroup.isHubCluster
#      value: false
#    clusterSelector:
#      matchExpressions:
#      - key: vendor
#        operator: In
#        values:
#          - OpenShift
#
#  namespaces:
#  - open-cluster-management
#
#  subscriptions:
#  - name: advanced-cluster-management
#    namespace: open-cluster-management
#    source: redhat-operators
#    channel: release-2.3
#    csv: v2.3.2
#
#  projects:
#  - datacenter
# 
#  applications:
#  - name: acm
#    namespace: default
#    project: datacenter
#    path: applications/acm
