apiVersion: ocs.openshift.io/v1
kind: OCSInitialization
metadata:
  name: {{ .Values.toolbox.name }}
  namespace: {{ .Values.odf.namespace }}
spec:
  enableCephTools: {{ .Values.toolbox.enableCephTools }}
