{{- range .Values.rbac.roles -}}
{{- if $.Values.rbac.createRoleBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: {{ .name }}-roleBinding
{{- if eq .clusterRoleBinding false }}
  namespace: {{ .namespace }}
{{- end }}
roleRef:
  apiGroup: ""
  kind: {{ .binding.kind }}
  name: {{ .name }}
subjects:
- kind: {{ .binding.subjects.kind }}
  name: {{ .binding.subjects.name }}
  namespace: {{ .binding.subjects.namespace }}
{{- end }}
{{- end }}
