apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xraylab-mgmt
  namespace: openshift-storage
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xraylab-mgr-role
  namespace: xraylab-1
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xraylab-mgmt-binding
  namespace: openshift-storage
roleRef:
  apiGroup: ""
  kind: Role
  name: xraylab-mgmt
subjects:
- kind: ServiceAccount
  name: xraylab-mgr
  namespace: xraylab-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xraylab-mgr-binding
  namespace: xraylab-1
roleRef:
  apiGroup: ""
  kind: Role
  name: xraylab-mgr-role
subjects:
- kind: ServiceAccount
  name: xraylab-mgr
  namespace: xraylab-1
