kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xraylabdb
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.global.datacenter.storageClassName }}
  volumeMode: Filesystem
