kind: Job
apiVersion: batch/v1
metadata:
  name: wait-for-deployment-complete
  namespace: '{{ .Values.global.xraylab.namespace }}'
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "-5"
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=available deploy/noobaa-endpoint --timeout=900s -n openshift-storage
          oc wait --for=condition=available dc/xraylabdb --timeout 900s -n xraylab-1
        name: wait-for-deployment-complete
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccount: openshift-gitops-argocd-application-controller
      serviceAccountName: openshift-gitops-argocd-application-controller
      terminationGracePeriodSeconds: 60