s3:
  bucketSource: 
  bucketBaseName: "xraylab-1"

#Changing to ODF vs OCS
odf:
  serviceUrl: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"
  externalUrl: "https://s3-rgw-openshift-storage"
  targetBucket: com.redhat.jrickard.xray-source