apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-user
  namespace: '{{ .Values.global.xraylab.namespace }}'
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-5"
data:
  wait-for-user.sh: |
    #!/bin/bash
    RC=1
    while [ ${RC} -eq 1 ]
      do
        echo "Waiting for cephObjectStoreUser creation"
        oc get secret rook-ceph-object-user-ocs-storagecluster-cephobjectstore-xraylab-1 -n openshift-storage
        RC=$?
      done
