apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: wait-for-odf-noobaa-endpoint-deployment
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
{{- include "objectStoreUser.waitForNbEP" . | nindent 10 }}
        name: noobaa-endpoint-deployment-pause
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: openshift-gitops-argocd-application-controller
      serviceAccountName: openshift-gitops-argocd-application-controller
      terminationGracePeriodSeconds: 30
