apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.app }}
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  selector:
    app: {{ .Values.kafka.app }}
  ports:
    - protocol: {{ .Values.kafka.service.protocol }}
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}