apiVersion: v1
kind: ConfigMap
metadata:
  name: create-s3-secret
  namespace: '{{ .Values.global.xraylab.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  create-s3-secret.sh: |
    #!/bin/bash
    AWS_ACCESS_KEY_ID=$(oc extract -n openshift-storage secret/rook-ceph-object-user-ocs-storagecluster-cephobjectstore-xraylab-1 --keys=AccessKey --to=-)
    AWS_SECRET_ACCESS_KEY=$(oc extract -n openshift-storage secret/rook-ceph-object-user-ocs-storagecluster-cephobjectstore-xraylab-1 --keys=SecretKey --to=-)
    oc create secret generic s3-secret-bck --from-literal=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --from-literal=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -n {{ .Values.global.xraylab.namespace }}