apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
  name: label-odf-nodes
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
{{- include "odf.nodeLabels" . | nindent 10 }}
        name: label-odf-nodes
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: openshift-gitops-argocd-application-controller
      serviceAccountName: openshift-gitops-argocd-application-controller
      terminationGracePeriodSeconds: 30

