apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreSync
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Values.rbac.serviceAccount.namespace }}
