apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Values.rbac.serviceAccount.namespace }}
