apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rolebinding
  namespace: xraylab-1
  annotations:
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: ""
  kind: Role
  name: grafana-project-mgr
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: xraylab-1