apiVersion: v1
kind: ConfigMap
metadata:
  name: buckets-config
  namespace: "{{ .Values.global.xraylab.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "15"
data:
  bucket-source: "{{ .Values.global.xraylab.s3.bucketSource }}"
  bucket-base-name: "{{ .Values.global.xraylab.s3.bucketBaseName }}"
