- name: Generate the db-secret template
  kubernetes.core.helm_template:
    chart_ref: "{{ pattern_repo_dir }}/secrets"
    output_dir: "{{ helm_output_dir }}"
    values_files:
      - "{{ pattern_repo_dir }}/values-global.yaml"
      - "{{lookup('env', 'HOME')}}/values-secret.yaml"

- name: Apply the rendered template
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '/tmp/secrets/templates/db-secret.yaml') }}"
